version: '3.6'
services:
  iustitia-postgres:
    image: postgres:12
    # restart: always
    env_file:
      - ./.env.development
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/pocz_project/data

volumes:
  db_data:
