service: test-api

frameworkVersion: "2"

projectDir: ../../

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  variables: ${file(../../serverless.yml):custom.variables}

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, "development"}
  environment:
    NODE_ENV: ${self:provider.stage}
  lambdaHashingVersion: 20201221
  region: ${file(../../serverless.yml):provider.region}
  tracing:
    lambda: true
  iamRoleStatements:
    - ${file(../../serverless.yml):custom.lambdaPolicyXRay}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:provider.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:provider.stage}-ApiGatewayRestApiRootResourceId
    
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /hello
          method: get
          cors: true
