service: test-api

frameworkVersion: "2"

projectDir: ../../

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  variables: ${file(../../serverless.yml):custom.variables}

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, "development"}
  lambdaHashingVersion: 20201221
  region: us-east-1
  environment:
    NODE_ENV: ${self:provider.stage}
  tracing:
    lambda: true
  iamRoleStatements:
    - ${file(../../serverless.yml):custom.lambdaPolicyXRay}
    
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
