org: gugazimmermann
app: pocz-api
service: model

resources:
  - Description: Model Folder for ${env:PROJECT_NAME}

frameworkVersion: "2"
useDotenv: true
variablesResolutionMode: 20210326

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  bundle:
    ignorePackages:
      - pg-native

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, "development"}
  region: us-east-1
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: ${self:provider.stage}
  tracing:
    lambda: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:provider.stage}-ApiGatewayRestApiId
    restApiRootResourceId:
      'Fn::ImportValue': ${self:provider.stage}-ApiGatewayRestApiRootResourceId
