name: Production Build
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Create env file
        run: |
          touch .env.production
          echo PROJECT_NAME=${{ secrets.PROJECT_NAME }} >> .env.production
          echo PROJECT_WEBSITE_NAME=${{ secrets.PROJECT_WEBSITE_NAME }} >> .env.production
          echo PROJECT_WEBSITE_URL=${{ secrets.PROJECT_WEBSITE_URL }} >> .env.production
          echo PROJECT_APP_URL=${{ secrets.PROJECT_APP_URL }} >> .env.production
          echo PROJECT_API_URL=${{ secrets.PROJECT_API_URL }} >> .env.production
          echo PROJECT_API_DOMAIN=${{ secrets.PROJECT_API_DOMAIN }} >> .env.production
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env.production
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env.production
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env.production
          echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env.production
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env.production
          cat .env.production
          cp .env.production ./.env.development
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Serverless Authentication
        run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}
      - name: Install NPM dependencies
        run: yarn install
      - name: Run Tests
        run: yarn test
      - name: Deploy Production
        run: |
          echo $SERVERLESS_ACCESS_KEY
          yarn deploy:prod
        env:
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
